### ISSUE TITLE
Penalty being applied for both boarding and alighting transit route

### ISSUE THREAD

**Issue by kuanb** [UDST/urbanaccess#40]
Heads up that the internal logic suggests that, while the boarding penalty (1/2 headway) from OSM network to transit network (`ped_to_transit_edges_df`) was intended to be applied to only that direction, the argument being passed to it (`net_connector_edges`) is actually both to and from edges. Thus, the library is applying a penalty for both the boarding and alighting from a transit route line onto a walk network.

Location of the issue: https://github.com/UDST/urbanaccess/blob/84478b7e6f91d0b1fc46d0eecae48b963a535271/urbanaccess/network.py#L166-L174

**Comment by sablanchard** [comment]
Hi @kuanb thanks for the report. I have quickly looked into it and I cannot replicate the issue it all looks like it should be correct to me.

What is happening is:
The mean headway gets calculated for each route stop pair then it gets joined to the transit and osm connector edge table by using only the `to` edge id where in this case only ids that match the route stop ids in the two tables are matched - the osm ids are not matched as these are not route stop ids. This results in the df below that eventually turns into the connector edge table:

![image](https://user-images.githubusercontent.com/8645022/30881342-564216ce-a2ba-11e7-8366-806e84c44e0c.png)

Note the osm to transit edges have a value in the mean column and the transit to osm edges have nans. When the mean is applied to the weight column only the values that are not nan are added to the weight which in this case are only the osm to transit edges.

I hope that makes it clear, let me know if you are seeing something different. If so, please send a script of the full workflow so that we can replicate it and highlight the values in the df table of interest. If you cannot replicate and this explanation makes sense also let me know and I will close this issue.

**Comment by kuanb** [comment]
Thanks Sam.

Given your above message, it sounds like the intent of these lines:
https://github.com/UDST/urbanaccess/blob/84478b7e6f91d0b1fc46d0eecae48b963a535271/urbanaccess/network.py#L269-L270

Is to replace the NaN values with just the original calculated walk time. 

If that is the case, then we may want to make that explicit and enforce it as only on that direction by updating using a Pandas `.loc[]` lookup to replace just those values.

In addition, we’ll want to make that explicit in the parameters, too:

```
    Parameters
    ----------
    ped_to_transit_edges_df : pandas.DataFrame
        DataFrame of the osm to transit connectors
```

Should acknowledge that what is being input is the combined (bi-directional) edges and then a add’tl kwargs could be `edge_tag_to_add_headway=‘osm_to_transit’` and then we can `.loc` by all tags that are not that and make their weighting just the value of distance.

This is also an opportunity to parameterize how distance/cost for the connector is calculated. For example, one could defensibly argue for no-cost (weight 0) connectors from transit to OSM network (plus headway cost). Parameterization would enable this customization.

**Comment by sablanchard** [comment]
Thanks @kuanb yes that is the intent of those lines. What you suggest is a clearer and cleaner way of doing that. You are correct, this would bring us one step closer to allowing custom parameterization of the connector cost.

One issue is that all the functions in urbanaccess assume travel cost in terms of time not distance so more work would have to go into making time a optional weight parameter throughout the tool so that raw distance could be used throughout. Distance is calculated throughout its just not exposed to the user via parameters.

I will close this issue but feel free to post in this open issue: https://github.com/UDST/urbanaccess/issues/36 the details on how to achieve the parameterization.
