### ISSUE TITLE
pyrosm for network download

### ISSUE THREAD

**Issue by knaaptime** [UDST/urbanaccess#61]
hey folks, thanks again for this library. I was wondering if you'd seen the recently released [pyrosm](https://pyrosm.readthedocs.io/en/latest/)? it's able to parse OSM data much faster than alternative methods, so might be a more performant way to construct networks. Just wanted to raise the possibility of incorporating it here

**Comment by sablanchard** [comment]
Hi @knaaptime ! Have not seen it but agreed it looks like it would be a great addition to speed things up on the OSM side. Could be an optional param as an addition to the https://github.com/UDST/urbanaccess/blob/dev/urbanaccess/osm/load.py#L76-L81 section if one has the local `.osm.pbf` file. Something we can consider in a future release. Thanks for bringing it to our attention!

Of course PRs are always welcome for anyone interesting in taking this on sooner rather than later.

**Comment by knaaptime** [comment]
this has been implemented on the [pyrosm side](https://pyrosm.readthedocs.io/en/latest/basics.html#export-to-pandana)(!) so i'll go ahead and close this (though it might be nice to link there from here)
