### ISSUE TITLE
gtfs import fails if `calendar_dates.txt` is missing

### ISSUE THREAD

**Issue by knaaptime** [UDST/urbanaccess#69]
calendar_dates.txt is an optional file, but [this line](https://github.com/UDST/urbanaccess/blob/09a0133af588b4ba5e1e8c4ac589b5f859d73a62/urbanaccess/gtfs/utils_format.py#L220) raises an error if it's missing. Could this be changed to a warning instead?

**Comment by sablanchard** [comment]
thanks for the report @knaaptime , if that file is missing that function should never be active. Its only active when there is a txt with that name in the directory via https://github.com/UDST/urbanaccess/blob/09a0133af588b4ba5e1e8c4ac589b5f859d73a62/urbanaccess/gtfs/load.py#L280. It looks like you may have that file but its empty with no records. 

I think in this case since its optional I agree it can be changed to a warning. I would want to run a test after the change to make sure allowing an empty df for that file wont impact anything else downstream. If you are open to it, would you like to make a PR with the change and then Ill run a test on it to double check things before we merge it?

**Comment by knaaptime** [comment]
yup, thats what i meant thanks. will PR

also, some feeds [like wmata](http://transitfeeds.com/p/wmata/75) go with calendar_dates.txt and omit calendar.txt, which is [technically allowed](https://developers.google.com/transit/gtfs/reference#calendartxt). Would you be open to relaxing the check [here](https://github.com/UDST/urbanaccess/blob/09a0133af588b4ba5e1e8c4ac589b5f859d73a62/urbanaccess/gtfs/load.py#L243) so that it passes so long as one of the two files is present (or is calendar.txt hardwired into the processing somehow?)

**Comment by sablanchard** [comment]
that sounds like a great idea @knaaptime . Its like that only because of legacy, the calendar_dates support was added later and is harder for most users to understand how to use correctly to subset the network so it was intentionally discouraged however, there is no need to do that now. 

In addition, if there is anything in the calendar dates workflow that you see could be improved or usability could be improved please let us know, open to suggestions.

Agreed in that approach to do a validation check to make sure that at least one of those two files are present and if they are that at least one of them is not empty. Much appreciated your contributions and suggestions!
